/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genio;

/**
 *
 * @author Emerson
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        lblFrase.setText("<html>de 1 a 5, qual numero estou pensando?</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JSpinner();
        btnAdvinhe = new javax.swing.JButton();
        lblFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 30));

        btnAdvinhe.setText("Adivinhar!");
        btnAdvinhe.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdvinhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvinheActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdvinhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, 30));

        lblFrase.setText("frase");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balão3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvinheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvinheActionPerformed
        // TODO add your handling code here:
        double num =1 + Math.random() * (6 - 1);
        int valor = (int)num;
        
        int palpite = Integer.parseInt(btnPalpite.getValue().toString());
        
        String f1 = "acertou!";
        String f2 = "errou!,pensei em " + valor;
        
        String res = (valor == palpite)?f1:f2;
        
        lblFrase.setText(res);
    }//GEN-LAST:event_btnAdvinheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvinhe;
    private javax.swing.JSpinner btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFrase;
    // End of variables declaration//GEN-END:variables
}
